"""empty message

Revision ID: 245f92aae52f
Revises: 207c8a79ea42
Create Date: 2015-06-03 16:54:08.351416

"""

# revision identifiers, used by Alembic.
revision = '245f92aae52f'
down_revision = '207c8a79ea42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
