"""empty message

Revision ID: 2ca102f1acfd
Revises: None
Create Date: 2015-05-28 09:45:51.371126

"""

# revision identifiers, used by Alembic.
revision = '2ca102f1acfd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
