"""empty message

Revision ID: 4dfc540fee0
Revises: 2ca102f1acfd
Create Date: 2015-05-28 11:58:04.636137

"""

# revision identifiers, used by Alembic.
revision = '4dfc540fee0'
down_revision = '2ca102f1acfd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('titles')
    op.drop_table('texts')
    op.drop_column('posts', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_table('texts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], [u'titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###
